Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/light_talk_app/forms.py
from flask_wtf import FlaskForm
from wtforms import  SubmitField,  SelectField,  FloatField, StringField
from wtforms.validators import InputRequired

class AddForm(FlaskForm):
  incorrect_sentence = StringField('Frase Incorrecta', [InputRequired()])
  correct_sentence_one = StringField('Frase Correcta 1', [InputRequired()], default="none")
  correct_sentence_two = StringField('Frase Correcta 2', [InputRequired()], default="none")
  correct_sentence_three = StringField('Frase Correcta 3', [InputRequired()], default="none")
  objective = SelectField('Objetivo', [InputRequired()], 
    choices=[('Genero', 'Genero'), ('Número', 'Número')])
  source = SelectField('Fuente', [InputRequired()], 
    choices=[('Inteligencia Artificial', 'Inteligencia Artificial'), ('Persona', 'Persona'), ('Lingüista', 'Lingüista')])
  submit = SubmitField('Añadir')

class SelectForm(FlaskForm):
  objective = SelectField('Objetivo', [InputRequired()], 
    choices=[('Genero', 'Genero'), ('Número', 'Número'), ('Otro', 'Otro')])
  source = SelectField('Fuente', [InputRequired()], 
    choices=[('Inteligencia Artificial', 'Inteligencia Artificial'), ('Persona', 'Persona'), ('Lingüista', 'Lingüista')])
  submit = SubmitField('Seleccionar')

class VerifyForm1(FlaskForm):
  incorrect_sentence = StringField('Frase Incorrecta', [InputRequired()])
  your_sentence = StringField('¿Cuál es la frase correcta?', [InputRequired()])
  objective = StringField('Objetivo', [InputRequired()])
  source = StringField('Fuente', [InputRequired()])
  submit = SubmitField('Verifica')

class VerifyForm2One(FlaskForm):
  incorrect_sentence = StringField('Frase Incorrecta', [InputRequired()])
  correct_sentence_one = StringField('Frase Correcta', [InputRequired()])
  your_sentence = StringField('Tu frase es:', [InputRequired()])
  result_string = StringField('Resultado:', [InputRequired()])
  objective = StringField('Objetivo', [InputRequired()])
  source = StringField('Fuente', [InputRequired()])

class VerifyForm2Two(FlaskForm):
  incorrect_sentence = StringField('Frase Incorrecta', [InputRequired()])
  correct_sentence_one = StringField('Frase Correcta 1', [InputRequired()])
  correct_sentence_two = StringField('Frase Correcta 2', [InputRequired()])
  your_sentence = StringField('Tu frase es:', [InputRequired()])
  result_string = StringField('Resultado:', [InputRequired()])
  objective = StringField('Objetivo', [InputRequired()])
  source = StringField('Fuente', [InputRequired()])

class VerifyForm2Three(FlaskForm):
  incorrect_sentence = StringField('Frase Incorrecta', [InputRequired()])
  correct_sentence_one = StringField('Frase Correcta 1', [InputRequired()])
  correct_sentence_two = StringField('Frase Correcta 2', [InputRequired()])
  correct_sentence_three = StringField('Frase Correcta 3', [InputRequired()])
  your_sentence = StringField('Tu frase es:', [InputRequired()])
  result_string = StringField('Resultado:', [InputRequired()])
  objective = StringField('Objetivo', [InputRequired()])
  source = StringField('Fuente', [InputRequired()])

class YourSentencesForm(FlaskForm):
  objective = SelectField('Objetivo', [InputRequired()], 
    choices=[('Genero', 'Genero'), ('Número', 'Número'), ('Todos', 'Todos')])
  source = SelectField('Fuente', [InputRequired()], 
    choices=[('Inteligencia Artificial', 'Inteligencia Artificial'), ('Persona', 'Persona'), ('Lingüista', 'Lingüista'), ('Todas', 'Todas')])
  submit = SubmitField('Seleccionar')

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/business/routes.py
from flask import render_template, Blueprint

business=Blueprint('business',__name__)

@business.route('/business')
def business_home():
  return render_template('business.html', title='business')

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/light_talk_app/__init__.py
#

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/light_talk_app/routes.py
from flask import render_template, Blueprint, redirect, url_for, flash, session
from capp.models import Sentence
from capp.light_talk_app.forms import AddForm, SelectForm, VerifyForm1, VerifyForm2One, VerifyForm2Two, VerifyForm2Three, YourSentencesForm
from flask_login import login_required, current_user
from capp import db
from sqlalchemy.sql.expression import func
import random

light_talk_app=Blueprint('light_talk_app',__name__)

@light_talk_app.route('/light_talk_app')
def light_talk_app_home():
    return render_template('/light_talk_app/light_talk_app.html', title='light_talk_app')

#Add a new sentence
@light_talk_app.route('/light_talk_app/añadir_frase', methods=['GET','POST'])
@login_required
def add_sentence():
    form = AddForm()
    if form.validate_on_submit():
        incorrect_sentence = form.incorrect_sentence.data
        correct_sentence_one = form.correct_sentence_one.data
        correct_sentence_two = form.correct_sentence_two.data
        correct_sentence_three = form.correct_sentence_three.data
        your_sentence = "none"
        objective = form.objective.data
        source = form.source.data
        result_string = "none"
        result_num= "nan"
        group = 'general'
        university = 'University of Salamanca'
        year = 2024
 
        sentence = Sentence(incorrect_sentence=incorrect_sentence, correct_sentence_one=correct_sentence_one, correct_sentence_two=correct_sentence_two, correct_sentence_three=correct_sentence_three, correct_sentence_four="none", your_sentence=your_sentence, objective=objective, source=source, result_string=result_string, result_num=result_num,  group=group, university=university, year=year, author=current_user)
        db.session.add(sentence)
        db.session.commit()
        return redirect(url_for('light_talk_app.light_talk_app_home'))
    return render_template('light_talk_app/add_sentence.html', title='add sentence', form=form)

#Select a sentence
@light_talk_app.route('/light_talk_app/selecciona_frase', methods=['GET','POST'])
@login_required
def select_sentence():
    form = SelectForm()
    if form.validate_on_submit():
        objective = form.objective.data
        source = form.source.data
        #Sentence
        sentence = Sentence.query.filter_by(author=current_user). \
            filter(Sentence.objective == objective).\
            filter(Sentence.source == source).\
            order_by(func.random()).first()
        if sentence is None:
            session["incorrect_sentence"]="none"
            session["correct_sentence_one"]="none"
            session["correct_sentence_two"]="none"
            session["correct_sentence_three"]="none"
            session["objective"]=objective
            session["source"]=source 
            session["message"]="No has añadido ninguna frase con ese objetivo y fuente. Por favor, añade una frase con ese objetivo y fuente para continuar."
        else:
            session["incorrect_sentence"]=sentence.incorrect_sentence 
            session["correct_sentence_one"]=sentence.correct_sentence_one
            session["correct_sentence_two"]=sentence.correct_sentence_two
            session["correct_sentence_three"]=sentence.correct_sentence_three
            session["objective"]=sentence.objective
            session["source"]=sentence.source   
            session["message"]="Hay frases añadidas con ese objetivo y fuente"         
        return redirect(url_for('light_talk_app.check_sentence'))
    return render_template('light_talk_app/select_sentence.html', title='select sentence', form=form)

#Check sentence
@light_talk_app.route('/light_talk_app/tu_respuesta', methods=['GET','POST'])
@login_required
def check_sentence():
    form=VerifyForm1()
    incorrect_sentence=session["incorrect_sentence"]
    correct_sentence_one=session["correct_sentence_one"]
    correct_sentence_two=session["correct_sentence_two"]
    correct_sentence_three=session["correct_sentence_three"]
    objective=session["objective"]
    source=session["source"]
    message=session["message"]
    form.incorrect_sentence.data=incorrect_sentence
    form.objective.data=objective
    form.source.data=source
    if form.validate_on_submit():
        Sentence.query.filter_by(author=current_user). \
            filter(Sentence.incorrect_sentence == incorrect_sentence).delete()
        db.session.commit()
        if form.your_sentence.data==correct_sentence_one or form.your_sentence.data==correct_sentence_two or form.your_sentence.data==correct_sentence_three:
            your_sentence=form.your_sentence.data
            result_string = "Correcto"
            result_num= 1
            group = 'general'
            university = 'University of Salamanca'
            year = 2024

            session["your_sentence"]=your_sentence
            session["result_string"]=result_string
            session["result_num"]=result_num

            sentence = Sentence(incorrect_sentence=incorrect_sentence, correct_sentence_one=correct_sentence_one, correct_sentence_two=correct_sentence_two, correct_sentence_three=correct_sentence_three, correct_sentence_four="none", your_sentence=your_sentence, objective=objective, source=source, result_string=result_string, result_num=result_num,  group=group, university=university, year=year, author=current_user)
            db.session.add(sentence)
            db.session.commit()
        else:
            your_sentence=form.your_sentence.data
            result_string = "Incorrecto"
            result_num= 0
            group = 'general'
            university = 'University of Salamanca'
            year = 2024

            session["your_sentence"]=your_sentence
            session["result_string"]=result_string
            session["result_num"]=result_num

            sentence = Sentence(incorrect_sentence=incorrect_sentence, correct_sentence_one=correct_sentence_one, correct_sentence_two=correct_sentence_two, correct_sentence_three=correct_sentence_three, correct_sentence_four="none", your_sentence=your_sentence, objective=objective, source=source, result_string=result_string, result_num=result_num,  group=group, university=university, year=year, author=current_user)
            db.session.add(sentence)
            db.session.commit()
        return redirect(url_for('light_talk_app.result_sentence'))
    return render_template('light_talk_app/your_solution.html', form=form, message=message, objective=objective, source=source)

#Result Sentence
@light_talk_app.route('/light_talk_app/tu_resultado', methods=['GET','POST'])
@login_required
def result_sentence():
    correct_sentence_one=session["correct_sentence_one"]
    correct_sentence_two=session["correct_sentence_two"]
    correct_sentence_three=session["correct_sentence_three"]
    if correct_sentence_one != "none" and correct_sentence_two == "none" and correct_sentence_three == "none":
        form1=1
        form2=0
        form3=0
        form=VerifyForm2One() 
        form.incorrect_sentence.data=session["incorrect_sentence"]
        form.correct_sentence_one.data=session["correct_sentence_one"]
        form.your_sentence.data=session["your_sentence"]
        form.result_string.data=session["result_string"]
        form.objective.data=session["objective"]
        form.source.data=session["source"]
    elif correct_sentence_one != "none" and correct_sentence_two != "none" and correct_sentence_three == "none":
        form1=0
        form2=1
        form3=0
        form=VerifyForm2Two() 
        form.incorrect_sentence.data=session["incorrect_sentence"]
        form.correct_sentence_one.data=session["correct_sentence_one"]
        form.correct_sentence_two.data=session["correct_sentence_two"]
        form.your_sentence.data=session["your_sentence"]
        form.result_string.data=session["result_string"]
        form.objective.data=session["objective"]
        form.source.data=session["source"]
    else:
        form1=0
        form2=0
        form3=1
        form=VerifyForm2Three() 
        form.incorrect_sentence.data=session["incorrect_sentence"]
        form.correct_sentence_one.data=session["correct_sentence_one"]
        form.correct_sentence_two.data=session["correct_sentence_two"]
        form.correct_sentence_three.data=session["correct_sentence_three"]
        form.your_sentence.data=session["your_sentence"]
        form.result_string.data=session["result_string"]
        form.objective.data=session["objective"]
        form.source.data=session["source"]
    return render_template('light_talk_app/your_result.html', form=form, form1=form1, form2=form2, form3=form3)

#Select your sentences
@light_talk_app.route('/light_talk_app/selecciona_tus_frases', methods=['GET','POST'])
@login_required
def select_your_sentences():
    form = YourSentencesForm()
    if form.validate_on_submit():
        objective = form.objective.data
        source = form.source.data
        session["objective"]=objective
        session["source"]=source
        return redirect(url_for('light_talk_app.your_sentences'))
    return render_template('light_talk_app/select_your_sentences.html', title='select your sentences', form=form)

#Select your sentences
@light_talk_app.route('/light_talk_app/tus_frases', methods=['GET','POST'])
@login_required
def your_sentences():
    form = YourSentencesForm()
    objective=session["objective"]
    source=session["source"]
    form.objective.data=session["objective"]
    form.source.data=session["source"]
    if objective != "Todos" and source != "Todas":
        sentences = Sentence.query.filter_by(author=current_user). \
                filter(Sentence.objective == objective).\
                filter(Sentence.source == source).\
                order_by(Sentence.date.desc()).all()

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/templates/light_talk_app/light_talk_app.html
{% extends "layout.html" %} {% block content %}

<!-- Header -->
<section class="section_header_light_talk_app">
  <div class="container">
    <div class="header_light_talk_app">
      <div class="box">
        <h1 style="font-size: 55px">
          <span class="text-logo"> Light Talk App</span>
        </h1>
        <p style="text-align: left">
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat
          dolores quos asperiores repellendus facilis cum illo aperiam odit
          doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente
          quisquam consectetur optio magnam voluptates omnis vel officia alias
          distinctio quas laborum reiciendis ratione inventore veniam,
          cupiditate doloribus dolore, eius natus a. Magni inventore
          consequuntur voluptas reprehenderit perferendis! Molestias aspernatur
          rem autem aut temporibus.
        </p>
        <div class="container_buttons_links_header_light_talk_app">
          <div class="btn">
            <a
              href="{{url_for('business.business_home')}}"
              class="btn btn-primary btn-lg mr-2"
              ,
              style="background-color: #007bff"
              >Business</a
            >
          </div>
          <!-- <div class="btn">
            <a
              href="#"
              class="btn btn-primary btn-lg mr-2"
              ,
              style="background-color: #007bff"
              >Tus frases</a
            >
          </div> -->
        </div>
      </div>
      <div class="box">
        <img
          src="{{url_for('static', filename='icons/light_talk_app.svg')}}"
          width="325"
          height="325"
          alt=""
        />
      </div>
    </div>
  </div>
</section>

<!-- light_talk_app_new_entry_main -->
<section class="section_light_talk_app_new_entry_main">
  <div class="container">
    <!-- <div class="light_talk_app_new_entry_main" style="display: block">
      <br />
      <h3 style="text-align: center">
      </h3>
    </div> -->

    <div class="light_talk_app_new_entry_main">
      <div class="box">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-pen-nib"></i>
        </div>
        <h3>Añade una frase</h3>
        <p>
          Aquí puedes <strong>añadir</strong> una frase a tu base de datos para
          personalizar tu aprendizaje del castellano.
        </p>
        <div class="section_container_buttons_light_talk_app_new_entry_main">
          <a
            class="btn_light_talk_app_new_entry_main"
            href="{{url_for('light_talk_app.add_sentence')}}"
            >Añadir</a
          >
        </div>
      </div>
      <div class="box">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-check-double"></i>
        </div>
        <h3>Selecciona una frase</h3>
        <p>
          Aquí puedes <strong>seleccionar</strong> una frase de tu base de datos
          para seguir mejorando en tu aprendizaje del castellano.
        </p>
        <div class="section_container_buttons_light_talk_app_new_entry_main">
          <a
            class="btn_light_talk_app_new_entry_main"
            href="{{url_for('light_talk_app.select_sentence')}}"
            >Seleccionar</a
          >
        </div>
      </div>
      <div class="box">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-square-poll-vertical"></i>
        </div>
        <h3>Tus frases y estadísticas</h3>
        <p>
          Aquí puedes <strong>ver y modificar</strong> tus frases. También puede
          <strong>ver</strong> tus resultados y estadísticas.
        </p>
        <div class="section_container_buttons_light_talk_app_new_entry_main">
          <a
            class="btn_light_talk_app_new_entry_main"
            href="{{url_for('light_talk_app.select_your_sentences')}}"
            >Tus frases</a
          >
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/templates/light_talk_app/select_sentence.html
{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-check-double"></i>
        </div>
        <h3>Selecciona una frase</h3>
        <p>
          Por favor, <strong>selecciona</strong> una frase a tu base de datos para
              personalizar tu aprendizaje del castellano.
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.objective.label(class="form-control-label") }}
                    {% if form.objective.errors %}
                        {{ form.objective(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.objective.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.objective(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                  {{ form.source.label(class="form-control-label") }}
                  {% if form.source.errors %}
                      {{ form.source(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.source.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.source(class="form-control form-control-lg") }}
                  {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_light_talk_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/templates/light_talk_app/your_sentences.html
{% extends "layout.html" %} {% block content %}

<!-- Selection Section -->
<section class="section_light_talk_app_new_entry_main">
  <div class="container">
    <div class="light_talk_app_new_entry_main">
      <div class="box">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-pen-nib"></i>
        </div>
        <h3>Añade una frase</h3>
        <!-- <p>
          Aquí puedes <strong>añadir</strong> una frase a tu base de datos para
          personalizar tu aprendizaje del castellano.
        </p> -->
        <div class="section_container_buttons_light_talk_app_new_entry_main">
          <a
            class="btn_light_talk_app_new_entry_main"
            href="{{url_for('light_talk_app.add_sentence')}}"
            >Añadir</a
          >
        </div>
      </div>
      <div class="box">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-check-double"></i>
        </div>
        <h3>Selecciona una frase</h3>
        <!-- <p>
          Aquí puedes <strong>seleccionar</strong> una frase de tu base de datos
          para seguir mejorando en tu aprendizaje del castellano.
        </p> -->
        <div class="section_container_buttons_light_talk_app_new_entry_main">
          <a
            class="btn_light_talk_app_new_entry_main"
            href="{{url_for('light_talk_app.select_sentence')}}"
            >Seleccionar</a
          >
        </div>
      </div>
      <div class="box">
        <div class="h1 mb-3" style="text-align: center">
          <i class="fa-solid fa-square-poll-vertical"></i>
        </div>
        <h3>Tus frases y estadísticas</h3>
        <!-- <p>
          Aquí puedes <strong>ver y modificar</strong> tus frases. También puede
          <strong>ver</strong> tus resultados y estadísticas.
        </p> -->
        <div class="section_container_buttons_light_talk_app_new_entry_main">
          <a
            class="btn_light_talk_app_new_entry_main"
            href="{{url_for('light_talk_app.select_your_sentences')}}"
            >Tus frases</a
          >
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Selection Section -->
<section class="section_light_talk_app_new_entry_main">
  <div class="container">
    <div class="light_talk_app_new_entry_main">
      <div class="box" style="background-color: #f29545"></div>

      <div class="box">
        <canvas id="correct_vs_incorrect"></canvas>
      </div>

      <div class="box" style="background-color: #f29545"></div>
    </div>
  </div>
</section>

<!-- Table Section -->
<section class="table_main">
  <div class="container">
    <div class="box"></div>
    <div class="box">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %} {% endif %} {% endwith %}
      <script>
        setTimeout(function () {
          var flashes = document.querySelectorAll(".alert");
          flashes.forEach((flash) => flash.remove());
        }, 5000);
      </script>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Usuario</th>
            <th scope="col">Fecha</th>
            <th scope="col">Frase Incorrecta</th>
            <th scope="col">Tu Frase</th>
            <th scope="col">Resultado</th>
            <th scope="col">Objetivo</th>
            <th scope="col">Fuente</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for sentence in sentences %}
          <tr>
            <th scope="row">{{ current_user.username }}</th>
            <td>{{ sentence.date.strftime("%m-%d-%Y") }}</td>
            <td>{{ sentence.incorrect_sentence }}</td>
            <td>{{ sentence.your_sentence }}</td>
            <td>{{ sentence.result_string }}</td>
            <td>{{ sentence.objective }}</td>
            <td>{{ sentence.source }}</td>
            <td>
              <a
                href="{{ url_for('light_talk_app.delete_sentence', sentence_id = sentence.id) }}"
                class="btn btn-outline-danger btn-sm"
                >Delete</a
              >
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div class="box"></div>
  </div>
</section>

{% block javascript %}
<script>

  Chart.scaleService.updateScaleDefaults('linear', {
                  ticks: {
                      min: 0
                  }
          });


          let correct_vs_incorrect_chart = new Chart(correct_vs_incorrect, {
                  type: 'pie',
                  data: {
                  labels: ['Correcto', 'Incorrecto'],
                      datasets: [{
                          label: "Correcto Vs Incorrecto",
                          data: [{{correct}}, {{incorrect}}],
                          backgroundColor: ['#f2935c', '#f2d95c'],

                          borderWidth: 1,
                          hoverBorderColor: "black",
                          hoverBorderWidth: 2,
                          hoverBackgroundColor: 'rgba(154, 245, 140)',
                          pointHoverRadius: 5
                      }],
                  },
                  options: {
                          title: {
                              display: true,
                                  text: "Tus resultados",
                                      fontSize: 20,
                                      fontColor: "black"
                          },
                          legend: {
                              position: "right",
                                  labels: {
                                  fontColor: "black"
                              },
                              display: true,
                          },

                          elements: {
                              hitRadius: 3,
                          }
                  }
              })
</script>
{% endblock%} {% endblock content %}

Cap 6. Tablas y Graficos/Seccion 1b - Final/capp/templates/light_talk_app/your_solution.html

{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">
        {% if message=="No has añadido ninguna frase con ese objetivo y fuente. Por favor, añade una frase con ese objetivo y fuente para continuar." %}
        No has añadido ninguna frase con ese objetivo <strong>({{objective}})</strong> y fuente <strong>({{source}})</strong>. Por favor, añade una frase con ese objetivo <strong>({{objective}})</strong> y fuente <strong>({{source}})</strong> para continuar.
        <div class="section_container_buttons_light_talk_app_new_entry_main">
            <a
              class="btn_light_talk_app_new_entry_main"
              href="{{url_for('light_talk_app.add_sentence')}}"
              >Añadir</a
            >
        </div>
        {% else %}
        <div class="h1 mb-3" style="text-align: center;">
            <i class="fa-solid fa-check-double"></i>
        </div>
        <h3>Escribe tu respuesta</h3>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.incorrect_sentence.label(class="form-control-label") }}
                    {% if form.incorrect_sentence.errors %}
                        {{ form.incorrect_sentence(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.incorrect_sentence.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.incorrect_sentence(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                  {{ form.your_sentence.label(class="form-control-label") }}
                  {% if form.your_sentence.errors %}
                      {{ form.your_sentence(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.your_sentence.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.your_sentence(class="form-control form-control-lg") }}
                  {% endif %}
                </div>

                <div class="form-group">
                    {{ form.objective.label(class="form-control-label") }}
                    {% if form.objective.errors %}
                        {{ form.objective(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.objective.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.objective(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                  {{ form.source.label(class="form-control-label") }}
                  {% if form.source.errors %}
                      {{ form.source(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.source.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.source(class="form-control form-control-lg") }}
                  {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_light_talk_app_new_entry_main") }}
              </div>
          </form>
        {% endif %}
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}