Cap 4. Bases de Datos y Validacion/Seccion 4b - Boilerplate/capp/light_talk_app/routes.py
from flask import render_template, Blueprint
from capp.light_talk_app.forms import AddForm
from capp.models import Sentence

light_talk_app=Blueprint('light_talk_app',__name__)

@light_talk_app.route('/light_talk_app')
def light_talk_app_home():
    return render_template('/light_talk_app/light_talk_app.html', title='light_talk_app')

#Add a new sentence
@light_talk_app.route('/light_talk_app/añadir_frase', methods=['GET','POST'])
def add_sentence():
    form = AddForm()
    return render_template('light_talk_app/add_sentence.html', title='add sentence', form=form)
    

Cap 4. Bases de Datos y Validacion/Seccion 4b - Boilerplate/capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('¡Tu cuenta ha sido creada! ¡Ahora puedes iniciar sesión!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        flash('¡Has iniciado sesión! ¡Ahora puedes empezar a utilizar nuestra aplicación Light Talk!', 'success')
        return redirect(url_for('home.home_home'))
    else:
        flash('No se pudo iniciar sesión. ¡Verifique su correo electrónico y contraseña!', 'danger') 
  return render_template('users/login.html', title='login', form=form)

Cap 4. Bases de Datos y Validacion/Seccion 4b - Boilerplate/capp/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <!-- Header -->
  <section class="section_header_home">
    <div class="container">
      <div class="header_home">
        <div class="box">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %}
          <script>
            setTimeout(function () {
              var flashes = document.querySelectorAll(".alert");
              flashes.forEach((flash) => flash.remove());
            }, 5000);
          </script>
          <h1 style="font-size: 55px"><span class="text-logo"> Home</span></h1>
          <p style="text-align: left">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat
            dolores quos asperiores repellendus facilis cum illo aperiam odit
            doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente
            quisquam consectetur optio magnam voluptates omnis vel officia alias
            distinctio quas laborum reiciendis ratione inventore veniam,
            cupiditate doloribus dolore, eius natus a. Magni inventore
            consequuntur voluptas reprehenderit perferendis! Molestias aspernatur
            rem autem aut temporibus.
          </p>
          <div class="container_buttons_links_header_home">
            <div class="btn">
              <a
                href="#"
                class="btn btn-primary btn-lg mr-2"
                ,
                style="background-color: #007bff"
                >Register</a
              >
            </div>
            <div class="btn">
              <a
                href="#"
                class="btn btn-primary btn-lg mr-2"
                ,
                style="background-color: #007bff"
                >Login</a
              >
            </div>
          </div>
        </div>
        <div class="box">
          <img
            src="{{url_for('static', filename='icons/home.svg')}}"
            width="325"
            height="325"
            alt=""
          />
        </div>
      </div>
    </div>
  </section>

  <!-- Developers -->
  <section class="section_developers">
    <div class="container">
      <div class="developers" style="display: block">
        <h1 style="text-align: center">Our Team</h1>
        <p>
          Nuestro equipo de lingüistas, economistas, educadores y programadores….
          ... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia, ut?
          Praesentium quidem sunt perspiciatis doloremque fugiat nesciunt quaerat
          ullam, pariatur iure unde ratione ipsum adipisci repellendus,
          repudiandae hic sit, temporibus molestias corrupti aut soluta sequi!
          Architecto deleniti expedita nisi repudiandae enim eum quas odit facilis
          placeat neque porro, animi incidunt consectetur. Maiores ab saepe
          tempora, iure asperiores beatae suscipit cum ipsum, rerum doloremque
          reprehenderit dolorum debitis, aliquam quasi. Maiores corporis fuga
          quasi nesciunt dolor iste, inventore necessitatibus unde!
        </p>
      </div>

      <div class="developers">
        <div class="box">
          <img
            src="https://randomuser.me/api/portraits/men/10.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 1</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box">
          <img
            src="https://randomuser.me/api/portraits/women/11.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 2</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box">
          <img
            src="https://randomuser.me/api/portraits/men/12.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 3</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
      </div>

      <div class="developers">
        <div class="box2">
          <img
            src="https://randomuser.me/api/portraits/women/12.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 4</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box2">
          <img
            src="https://randomuser.me/api/portraits/women/13.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 5</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box2"></div>
      </div>
    </div>
  </section>

{% endblock content %}


Cap 4. Bases de Datos y Validacion/Seccion 4b - Boilerplate/capp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Font Awesome code -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!--Import the Bootstrap CSS file:-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />

    <!-- CSS code -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='layout.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='home.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='user.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='light_talk_app.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='business.css') }}"
    />

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>home</title>
    {% endif %}
  </head>
  <body>
    <section class="section_light_talk_app_navbar">
      <div class="container">
        <div class="light_talk_app_navbar">
          <h1 class="logo">
            <span class="text-logo"
              ><i class="fa-solid fa-comment-dots"></i> Light Talk</span
            >
            App
          </h1>
          <nav>
            <ul>
              <li>
                <a href="{{url_for('users.register')}}">Register</a>
              </li>
              <li>
                <a href="{{url_for('users.login')}}">Log in</a>
              </li>
              <li>
                <a href="{{url_for('home.home_home')}}">Home</a>
              </li>
              <li>
                <a href="{{url_for('business.business_home')}}">Business</a>
              </li>
              <li>
                <a href="{{url_for('light_talk_app.light_talk_app_home')}}"
                  >Light Talk App</a
                >
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </section>

    {% block content %} {% endblock %}

    <section class="section_footer">
      <div class="container">
        <div class="footer">
          <h1>
            Light Talk App
            <a href="#">
              <i class="fa-solid fa-circle-up" style="color: #568c63"></i>
            </a>
          </h1>
        </div>
      </div>
    </section>

    </body>
</html>

Cap 4. Bases de Datos y Validacion/Seccion 4b - Boilerplate/capp/templates/light_talk_app/add_sentence.html

{% extends "layout.html" %}
{% block content %}

<section class="new_entry">
  <div class="container">
      <div class="box">

      </div>
      <div class="box">   
        <div class="h1 mb-3" style="text-align: center;">
          <i class="fa-solid fa-pen-nib"></i>
        </div>
        <h3>Añade una frase</h3>
        <p>
            Por favor, <strong>añade</strong> una frase a tu base de datos para
            personalizar tu aprendizaje del castellano.
        </p>
          <form method="POST" action="">
              {{ form.csrf_token }}
              <fieldset class="form-group">

                <div class="form-group">
                    {{ form.incorrect_sentence.label(class="form-control-label") }}
                    {% if form.incorrect_sentence.errors %}
                        {{ form.incorrect_sentence(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.incorrect_sentence.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.incorrect_sentence(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                  {{ form.correct_sentence_one.label(class="form-control-label") }}
                  {% if form.correct_sentence_one.errors %}
                      {{ form.correct_sentence_one(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.correct_sentence_one.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.correct_sentence_one(class="form-control form-control-lg") }}
                  {% endif %}
                </div>

                <div class="form-group">
                    {{ form.correct_sentence_two.label(class="form-control-label") }}
                    {% if form.correct_sentence_two.errors %}
                        {{ form.correct_sentence_two(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.correct_sentence_two.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.correct_sentence_two(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.correct_sentence_three.label(class="form-control-label") }}
                    {% if form.correct_sentence_three.errors %}
                        {{ form.correct_sentence_three(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.correct_sentence_three.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.correct_sentence_three(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                
                <div class="form-group">
                    {{ form.objective.label(class="form-control-label") }}
                    {% if form.objective.errors %}
                        {{ form.objective(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.objective.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.objective(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                  {{ form.source.label(class="form-control-label") }}
                  {% if form.source.errors %}
                      {{ form.source(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in form.source.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.source(class="form-control form-control-lg") }}
                  {% endif %}
                </div>

              </fieldset>
              </br>
              <div class="form-group">
                {{ form.submit(class="btn_light_talk_app_new_entry_main") }}
              </div>
          </form>
      </div>
      <div class="box">

      </div>
  </div>
</section> 

        
{% endblock content %}